platform :ios, "8.0"
inhibit_all_warnings!

pod 'CJAMacros', '~> 2.1'
pod 'CJALog', '~> 1.1.0'
pod 'MagicalRecord', '~> 2.2'
pod 'BIObjCHelpers', :path => '../'

target :BIObjCHelpersExampleTests do
    pod 'OCMockito', '~> 1.4.0'
end
