language: objective-c
xcode_project: BIObjCHelpers.xcodeproj
osx_image: xcode9.2

before_install:
- gem i cocoapods --no-ri --no-rdoc
- gem i slather --no-ri --no-rdoc
- brew uninstall xctool; brew install xctool --HEAD;

script:
- xctool -project BIObjCHelpers.xcodeproj -scheme BIObjCHelpers run-tests -test-sdk iphonesimulator11.2 -parallelize

after_success: slather
