language: objective-c
xcode_project: BIObjCHelpers.xcodeproj
osx_image: xcode7.3

before_install:
- gem i cocoapods --no-ri --no-rdoc
- gem i slather --no-ri --no-rdoc
- brew uninstall xctool; brew install xctool --HEAD;

script:
- xctool test -project BIObjCHelpers.xcodeproj -scheme BIObjCHelpers -sdk iphonesimulator9.3 -destination "platform=iOS Simulator,name=iPhone 6,OS=9.3" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success: slather
