language: objective-c
xcode_project: BIObjCHelpers.xcodeproj
osx_image: xcode9.2

before_install:
- gem i cocoapods --no-ri --no-rdoc
- gem i slather --no-ri --no-rdoc
- brew uninstall xctool; brew install xctool --HEAD;

script:
- xctool test -project BIObjCHelpers.xcodeproj -scheme BIObjCHelpers -sdk iphonesimulator11.2 -destination "platform=iOS Simulator,name=iPhone 8,OS=11.0"

after_success: slather
