language: objective-c
xcode_project: BIObjCHelpers.xcodeproj
osx_image: xcode9.2

before_install:
- gem i cocoapods --no-ri --no-rdoc
- gem i slather --no-ri --no-rdoc

script:
xcodebuild test -project BIObjCHelpers.xcodeproj -scheme BIObjCHelpers -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' -enableCodeCoverage YES

after_success: slather
