language: objective-c
xcode_workspace: BIObjCHelpers.xcworkspace
osx_image: beta-xcode6.3

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - sudo easy_install cpp-coveralls

script:
  - xctool test -workspace BIObjCHelpers.xcworkspace -scheme BIObjCHelpers -sdk iphonesimulator8.3 -destination "platform=iOS Simulator,name=iPhone 6,OS=8.3"

after_success: 
  ./coveralls.rb --exclude-folder ./BIObjCHelpersTests --exclude-folder ./Pods
