language: objective-c
xcode_workspace: BIObjCHelpers.xcworkspace
osx_image: beta-xcode6.3

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - rvm use $RVM_RUBY_VERSION

install:
  - bundle install --without=documentation --path ../travis_bundle_dir

script:
  - xctool test -workspace BIObjCHelpers.xcworkspace -scheme BIObjCHelpers -sdk iphonesimulator8.3 -destination "platform=iOS Simulator,name=iPhone 6,OS=8.3"

after_success: slather
