language: objective-c
xcode_workspace: BIObjCHelpers.xcworkspace
osx_image: xcode7

before_install:
- gem i cocoapods --no-ri --no-rdoc
- gem i slather --no-ri --no-rdoc
- brew uninstall xctool; brew install xctool --HEAD;

script:
- xctool test -workspace BIObjCHelpers.xcworkspace -scheme BIObjCHelpersTests -sdk iphonesimulator9.0 -destination "platform=iOS Simulator,name=iPhone 6,OS=9.0"

after_success: slather
